apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-website
  labels:
    app: nginx-website-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: beer-rating-frontend
            port:
              number: 8179
